### ISSUE TITLE
Tags that cover multiple cells (feature request)

### ISSUE THREAD

**Issue by beasteers** [post2web/nbloader#1]
First of all, nice work on this package! I'm excited to start using it in one of my projects. One thing that would be helpful is if we were able to add tags that wrap multiple cells. 

Looking through the source code, it seems like I can do what I want by adding tags with a certain name to each cell that I want to run so it's not super urgent, but it would be cleaner if we can just mark the beginning and end of a tag. 

What we can do now:
```python
# mytag
```

```python
# mytag
```

```python
# mytag
```

```python
# mytag
```

What I'm proposing:
```python
# begin:mytag
```

```python
...
```

```python
...
```

```python
# end:mytag
```

I'm still unsure about what syntax we'd want to use for that, but it's the basic idea.

Another fun thought could be to tag cells using markdown headings. I think this could be quite semantic and useful. This might be a nice first step and would keep the API cleaner.

**Comment by post2web** [comment]
Those are all good suggestions. I would merge a PR if you want to implement it.

**Comment by beasteers** [comment]
Great! I'll look into it when I get a couple minutes.
